// Generated by scripts/api-scanner.ts from live api.sr.se responses.
// Do not edit by hand; run `yarn api:types` in server/ instead.

package se.venastrom.vradio.api.sr.programs

import kotlinx.serialization.Serializable

@Serializable
data class Socialmediaplatform(
  val platform: String,
  val platformurl: String,
)

@Serializable
data class Channel(
  val id: Int,
  val name: String,
)

@Serializable
data class Programcategory(
  val id: Int,
  val name: String,
)

@Serializable
data class Program(
  val description: String,
  val broadcastinfo: String? = null,
  val email: String,
  val phone: String,
  val programurl: String,
  val programslug: String? = null,
  val programimage: String,
  val programimagetemplate: String,
  val programimagewide: String,
  val programimagetemplatewide: String,
  val socialimage: String,
  val socialimagetemplate: String,
  val socialmediaplatforms: List<Socialmediaplatform>,
  val channel: Channel,
  val archived: Boolean,
  val hasondemand: Boolean,
  val haspod: Boolean,
  val responsibleeditor: String,
  val id: Int,
  val name: String,
  val programcategory: Programcategory? = null,
  val payoff: String? = null,
)

@Serializable
data class ProgramsResponse(
  val copyright: String,
  val programs: List<Program>,
)

