// Generated by scripts/kotlin-dto-gen.ts from src/types/api.ts.
// Do not edit by hand; run `yarn api:kotlin` in server/ instead.

package se.venastrom.vradio.api

import kotlinx.serialization.Serializable

@Serializable
data class ChannelDto(
  val id: Int,
  val name: String,
  val tagline: String,
  val image: String,
  /** Hex, e.g. "31a1bd". Used for per-channel accents. */
  val color: String,
  /**
   * Flattened from LiveAudio.url. Null for channels with no live stream, which
   * the client must treat as unplayable rather than assume.
   */
  val streamUrl: String?,
)

@Serializable
data class ChannelsResponse(
  val channels: List<ChannelDto>,
  /** Total across all pages, not this page's length. */
  val total: Int,
  /** Every channel id in order, so the client can render placeholders it has not paged in yet. */
  val allIds: List<Int>,
)

@Serializable
data class ProgramDto(
  val id: Int,
  val name: String,
  val description: String,
  val image: String,
  val channelId: Int,
  val hasPod: Boolean,
)

@Serializable
data class ProgramsResponse(
  val programs: List<ProgramDto>,
  val total: Int,
  val allIds: List<Int>,
)

@Serializable
data class ApiError(
  val error: String,
)
