// Generated by scripts/kotlin-dto-gen.ts from src/types/api.ts.
// Do not edit by hand; run `yarn api:kotlin` in server/ instead.

package se.venastrom.vradio.api

import kotlinx.serialization.Serializable

@Serializable
data class ChannelDto(
  /** SR's numeric id, as a string. Ids are opaque here; never do arithmetic on them. */
  val id: String,
  val name: String,
  val tagline: String,
  val image: String,
  /** Hex, e.g. "31a1bd". Used for per-channel accents. */
  val color: String,
  /** Flattened from SR's nested liveaudio object. Always playable. */
  val streamUrl: String,
)

@Serializable
data class ChannelsResponse(
  val channels: List<ChannelDto>,
  /** Total across all pages, not this page's length. */
  val total: Int,
  /** Every channel id in order, so the client can render placeholders it has not paged in yet. */
  val allIds: List<String>,
)

@Serializable
data class ProgramDto(
  val id: String,
  val name: String,
  val description: String,
  val image: String,
  /** Null when SR lists a program against a channel its channels endpoint does not return. */
  val channelId: String?,
  val hasPod: Boolean,
)

@Serializable
data class ProgramsResponse(
  val programs: List<ProgramDto>,
  val total: Int,
  val allIds: List<String>,
)

@Serializable
data class ApiError(
  val error: String,
)
