// Generated by scripts/api-scanner.ts from live api.sr.se responses.
// Do not edit by hand; run `yarn api:types` in server/ instead.

package se.venastrom.vradio.api.sr.episodes

import kotlinx.serialization.Serializable

@Serializable
data class Program(
  val id: Int,
  val name: String,
)

@Serializable
data class Playlist(
  val duration: Int,
  val publishdateutc: String,
  val id: Int,
  val url: String,
  val statkey: String,
)

@Serializable
data class Broadcastfile(
  val duration: Int,
  val publishdateutc: String,
  val id: Int,
  val url: String,
  val statkey: String,
)

@Serializable
data class Broadcast(
  val availablestoputc: String? = null,
  val playlist: Playlist,
  val broadcastfiles: List<Broadcastfile>,
)

@Serializable
data class Broadcasttime(
  val starttimeutc: String,
  val endtimeutc: String,
)

@Serializable
data class Listenpodfile(
  val title: String,
  val description: String,
  val filesizeinbytes: Int,
  val program: Program,
  val availablefromutc: String,
  val duration: Int,
  val publishdateutc: String,
  val id: Int,
  val url: String,
  val statkey: String,
)

@Serializable
data class Downloadpodfile(
  val title: String,
  val description: String,
  val filesizeinbytes: Int,
  val program: Program,
  val availablefromutc: String,
  val duration: Int,
  val publishdateutc: String,
  val id: Int,
  val url: String,
  val statkey: String,
)

@Serializable
data class Episode(
  val id: Int,
  val title: String,
  val description: String,
  val url: String,
  val program: Program,
  val audiopreference: String,
  val audiopriority: String,
  val audiopresentation: String,
  val publishdateutc: String,
  val imageurl: String,
  val imageurltemplate: String,
  val photographer: String? = null,
  val broadcast: Broadcast? = null,
  val broadcasttime: Broadcasttime? = null,
  val channelid: Int? = null,
  val listenpodfile: Listenpodfile? = null,
  val downloadpodfile: Downloadpodfile? = null,
)

@Serializable
data class EpisodesResponse(
  val copyright: String,
  val episodes: List<Episode>,
)

