// Generated by scripts/api-scanner.ts from live api.sr.se responses.
// Do not edit by hand; run `yarn api:types` in server/ instead.

package se.venastrom.vradio.api.sr.channels

import kotlinx.serialization.Serializable

@Serializable
data class Liveaudio(
  val id: Int,
  val url: String,
  val statkey: String,
)

@Serializable
data class Channel(
  val image: String,
  val imagetemplate: String,
  val color: String,
  val tagline: String,
  val siteurl: String,
  val liveaudio: Liveaudio,
  val scheduleurl: String? = null,
  val channeltype: String,
  val xmltvid: String? = null,
  val id: Int,
  val name: String,
)

@Serializable
data class ChannelsResponse(
  val copyright: String,
  val channels: List<Channel>,
)

