/*
 * This file was generated by GitHub Copilot at the user's request.
 * If it misbehaves, feel free to delete or replace it.
 */

// One-time migration from legacy zustand-based stores into the new PlayProvider storage.
export function migrateFromLegacyZustand(): void {
  try {
    // SETTINGS STORE -> followed programs + channels
    const legacySettingsRaw = localStorage.getItem("settings-store");
    if (legacySettingsRaw) {
      try {
        const parsed = JSON.parse(legacySettingsRaw) as {
          state?: {
            settings?: {
              programIDs?: unknown;
              likedChannels?: unknown;
            };
          };
        };
        const settings = parsed?.state?.settings;

        if (!localStorage.getItem("followedPrograms") && settings?.programIDs && Array.isArray(settings.programIDs)) {
          const programIDs = (settings.programIDs as unknown[])
            .map((id) => Number(id))
            .filter((id) => Number.isFinite(id));
          if (programIDs.length > 0) {
            localStorage.setItem("followedPrograms", JSON.stringify(programIDs));
          }
        }

        if (!localStorage.getItem("followedChannels") && settings?.likedChannels && Array.isArray(settings.likedChannels)) {
          const likedChannels = (settings.likedChannels as unknown[])
            .map((id) => Number(id))
            .filter((id) => Number.isFinite(id));
          if (likedChannels.length > 0) {
            localStorage.setItem("followedChannels", JSON.stringify(likedChannels));
          }
        }
      }
      catch (error) {
        console.error("Failed to migrate legacy settings-store:", error);
      }
    }

    // PROGRESS STORE -> progressDB
    const legacyProgressRaw = localStorage.getItem("progress-store");
    if (legacyProgressRaw && !localStorage.getItem("progressDB")) {
      try {
        type LegacyEpisodeProgress = number | { elapsed?: number };
        type LegacyProgressStore = {
          state?: {
            episodeProgressMap?: Record<string, LegacyEpisodeProgress>;
          };
        };

        const parsed = JSON.parse(legacyProgressRaw) as LegacyProgressStore;
        const map = parsed?.state?.episodeProgressMap;
        if (map && typeof map === "object") {
          const migrated: Record<string, number> = {};
          for (const [episodeID, value] of Object.entries(map)) {
            if (!episodeID) continue;
            let elapsedNumber: number | null = null;

            if (typeof value === "number") {
              elapsedNumber = value;
            }
            else if (value && typeof value === "object" && "elapsed" in value && typeof value.elapsed === "number") {
              elapsedNumber = value.elapsed;
            }

            if (elapsedNumber !== null && Number.isFinite(elapsedNumber) && elapsedNumber > 0) {
              migrated[episodeID] = elapsedNumber;
            }
          }

          if (Object.keys(migrated).length > 0) {
            localStorage.setItem("progressDB", JSON.stringify(migrated));
          }
        }
      }
      catch (error) {
        console.error("Failed to migrate legacy progress-store:", error);
      }
    }
  }
  catch (error) {
    console.error("Legacy zustand migration failed:", error);
  }
}
